# はんなりPython Python3.8 hands on
- Python3.8がリリースされました
- https://blog.python.org/
![title](python38.png)
- 3.8 What's New? ドキュメント　https://docs.python.org/3/whatsnew/3.8.html
- [これまでのバージョンアップでの主要な変更点](https://gitpitch.com/pyconjp/slides/master?p=osc2019fukuoka#/7) ([@terapon](https://twitter.com/terapyon))
### というわけで、基礎的な部分を触りながら新機能にも触れよう！というのが今回のハンズオンです。

In [290]:
# バージョン確認
!python3 -V

# or
import sys
print(sys.version_info)

Python 3.8.0
sys.version_info(major=3, minor=8, micro=0, releaselevel='final', serial=0)


## 3.8じゃない人はインストールしましょう
- 環境構築はpython.jpが参考になります
    - https://www.python.jp/install/install.html
- そのほか、Pythonでの開発を効率的に進めるためのツール
    - pyconjp2019 ビギナーセッション おだぎりあつしさん（[@aodag](https://twitter.com/aodag)）
    - https://www.slideshare.net/aodag/python-172432039?ref=https://pyconjp.connpass.com/event/135734/presentation/
    ## ツールたち
        - venv推奨
        - flake8
            - 静的チェックツール　
            - \$pip install flake8     
        - black 
            - コードフォーマッター
            - \$ pip install black     
        - mypy
            - type hint チェック 
            - \$ pip install mypy
            - アッキーさんLT資料　https://www.slideshare.net/hiroyaakita/python-174152843
        - pytest
            - ユニットテストフレームワーク 
            - \$ pip install pytest
        - tox
            - テスト用のvirtualenvの管理 
            - \$ pip install tox
    ## そのほか利用するもの
        - jupyter notebook | lab
        - pandas 
        - flask
        - django
      
    ## エディタ
        - いろいろあるので好きなので良いです。上のツールと連携できます。
            - VSCODE
            - emacs
            - vim
            - pycharm

In [291]:
!python3 -V

Python 3.8.0


## 本日のメニュー
- pythonインタプリンタを触る
- 様々なデータ型を触る
- データを制御する
- モジュールを使う
- 関数を作る
- クラスを作る
- エラーと例外

## まずは基本的なPythonの使い方から
参考: python tutorial https://docs.python.org/3/tutorial/interpreter.html     
日本語 https://docs.python.org/ja/3.7/tutorial/interpreter.html

### インタプリタ
- Pythonはインタプリタ型言語（コンパイラ型言語）
- Pythonで書いたコードをコンピュータが分かる言葉にしてくれる
- python（Mac）、py（Windows）でインタプリタを実行できる
- exit()で終了

In [226]:
3 + 3

6

In [227]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## 入力の種類
- すうじ
- もじ
- Bool

In [228]:
## 数字
print("2は", type(2))
print("\"2\"は", type("2"))
print("2.1は", type(2.1))

2は <class 'int'>
"2"は <class 'str'>
2.1は <class 'float'>


In [229]:
2 + 2

4

In [230]:
2 + "2"

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [231]:
print("はんなり" + "Python")
print("はんなり" "Python")

はんなりPython
はんなりPython


In [232]:
2 * "2"

'22'

In [233]:
_ * 2

'2222'

In [234]:
type(True)

bool

### 変数への代入
- 値を代入することができる
- マルチバイトな文字列も変数として扱える
- 関数も渡せる
- classも渡せる
- New! 式も渡せる(セイウチ演算子)

In [235]:
a = 10
print(a)

10


In [236]:
a, b, c, d, e = 10, 20, 30, 40, 50
print(a,b,c,d,e)

10 20 30 40 50


In [237]:
はんなり = "はんなりpython"
京都 = "はんなりpython"
print(はんなり, 京都)

はんなりpython はんなりpython


In [238]:
r = range
list(r(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [239]:
class human:
    def __init__(self, name, tall):
        self.name = name
        self.tall = tall
    
    def greet(self, words="はじめまして"):
        return ("こんにちは、{}".format(words))
    
h = human("hide", 180)
# クラスが渡された変数をインスタンス変数と呼ぶ

In [240]:
h.name

'hide'

In [241]:
h.tall

180

In [242]:
h.greet()

'こんにちは、はじめまして'

### 3.8の新機能セイウチ演算子 
- [リンク](https://docs.python.org/ja/3.8/whatsnew/3.8.html#assignment-expressions)
- 変数に式を代入できる
- セイウチ演算子の使用は、複雑さを減らしたり可読性を向上させる綺麗なケースに限るよう努めてください

In [243]:
seiuchi = (ab := 10)
print(seiuchi)
print(ab)

10
10


In [244]:
a = "abdcegfhjikdil"
if (n := len(a)) > 10:
    print("Hello, {}".format(n))

Hello, 14


## スライス

In [245]:
hanpy = "はんなりPython"
print(hanpy[0])
print(hanpy[:4])
print(hanpy[4:7])
print(hanpy[-6:])

は
はんなり
Pyt
Python


In [246]:
## リスト
L = list()
L0 = []
print(type(L), type(L0))

# リスト
# 後入先出は簡単

L0 = [1,2,3,4,5,6]

L0.append(7)

print("7を入れたリスト", L0)

L0.pop()

print("popをしたリスト", L0)
# 最後が取り除かれる

L0.pop(0)
# popで番号指定で、先頭を取り除くことの可能。でも遅いらしい

print("pop", L0)

<class 'list'> <class 'list'>
7を入れたリスト [1, 2, 3, 4, 5, 6, 7]
popをしたリスト [1, 2, 3, 4, 5, 6]
pop [2, 3, 4, 5, 6]


In [247]:
# 先入れ先出しは上の方法では遅い
# collections.dequeを使おうとのこと

from collections import deque

t = deque([1,2,3,4,5,6])

t.append(7)

print(t)

t.popleft()

print(t)

deque([1, 2, 3, 4, 5, 6, 7])
deque([2, 3, 4, 5, 6, 7])


In [248]:
# リスト内法表記
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [249]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [250]:
## 辞書型
d = dict()
d1 = {}
print(type(d), type(d1))

# タプル
t = ()

print(type(t))

# 集合型
s = set()
s1 = {1,2,3}

print(type(s), type(s1))

<class 'dict'> <class 'dict'>
<class 'tuple'>
<class 'set'> <class 'set'>


In [259]:
# 辞書内法表記
a_dic = {i: i+2 for i in range(10)}
print(a_dic)

{0: 2, 1: 3, 2: 4, 3: 5, 4: 6, 5: 7, 6: 8, 7: 9, 8: 10, 9: 11}


In [251]:
s = {1,2,3}
s1 = {3,4,5}
s2 = {1,1,2,2,3,3,3,4,4,4}
print(s & s1)

{3}


In [252]:
s2

{1, 2, 3, 4}

In [253]:
hannari = ["a", "b", "c", "d", "e",]

In [254]:
hannari[1:3]

['b', 'c']

In [255]:
hannari_dict = {"a": 1, "b": 2, "c": 3, "d": 4, "e": 5}

In [256]:
hannari_dict[2]

KeyError: 2

In [257]:
hannari_dict["c"]

3

In [258]:
print(hannari_dict.items())
print(hannari_dict.keys())
print(hannari_dict.values())

dict_items([('a', 1), ('b', 2), ('c', 3), ('d', 4), ('e', 5)])
dict_keys(['a', 'b', 'c', 'd', 'e'])
dict_values([1, 2, 3, 4, 5])


### ファイルを作ったり読み込んだり
- openを使ってファイルを作る
    - なかってもopen
    - 閉じるのを忘れない(close)
- with 文
    - 閉じる命令をしないで良い

In [297]:
greeting = "こんにちは"
gr_file = open("greeting.txt", "w")
gr_file.write(greeting)
gr_file.close()

In [300]:
!cat greeting.txt
# windowsは
# !type greeting.txt

こんにちは

In [302]:
greeting = ["おはよう", "こんにちは", "おやすみ"]

with open("three_g.txt", "w") as f:
    for i in greeting:
        f.write(f"{i}\n")

In [303]:
!cat three_g.txt

おはよう
こんにちは
おやすみ


## 制御ツール
- while 文
- if 文
    - 条件分岐
- for 文
    - 繰り返す

### お手伝いツール    
- range 関数
    - [組み込み関数](https://docs.python.org/ja/3/library/functions.html)
    - [range関数](https://docs.python.org/ja/3/library/stdtypes.html#ranges)
- breakとcontinueのelse
- pass

In [45]:
cntl = "abcd" 

In [23]:
if cntl.startswith("a"):
    print("cntl is start with a")
else:
    print("not start with a")

cntl is start with a


In [24]:
for c in cntl:
    print(c)

a
b
c
d


In [25]:
range(10)

range(0, 10)

In [27]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [30]:
## 関数はhelp()で使い方が見れる
help(range)

Help on class range in module builtins:

class range(object)
 |  range(stop) -> range object
 |  range(start, stop[, step]) -> range object
 |  
 |  Return an object that produces a sequence of integers from start (inclusive)
 |  to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
 |  start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
 |  These are exactly the valid indices for a list of 4 elements.
 |  When step is given, it specifies the increment (or decrement).
 |  
 |  Methods defined here:
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |

In [32]:
list(range(0,100,10))

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]

## <span style="color: red;">課題</span>
- 1から10までの数値の入ったリストを作成しましょう
- 次にリストの値をキーに、その値の二乗をバリューにもつ辞書を作成しましょう
- 出来たら1000までの3で割れる数字で同じことをしましょう
- 100までの数のリストを作成し、if文とfor分を使って3で割れるリスト、5で割れるリスト、両方で割れるリストをそれぞれ作成しましょう。

### モジュールを使おう
- pythonの良いところはたくさんモジュールがあるところ
- [標準モジュール](https://docs.python.org/ja/3/library/index.html)
- モジュールというのは何かをやるためのプログラム
- これがあるので少しだけプログラミングが楽にできる
- 標準モジュール以外にも使えるモジュールがたくさん（外部モジュール）
- [PIPY](https://pypi.org/)

In [315]:
# 正規表現
import re
こハンター = re.compile("こ")
こハンター.search("こんにちは")

<re.Match object; span=(0, 1), match='こ'>

In [316]:
こハンター.search("ことしのことりはこんなにこんなんだ")

<re.Match object; span=(0, 1), match='こ'>

In [317]:
こハンター.findall("ことしのことりはこんなにこんなんだ")

['こ', 'こ', 'こ', 'こ']

In [318]:
こハンター.split("ことしのことりはこんなにこんなんだ")

['', 'としの', 'とりは', 'んなに', 'んなんだ']

In [319]:
# 日付を扱う
import datetime
datetime.datetime.now()

datetime.datetime(2019, 11, 10, 11, 3, 44, 413781)

In [314]:
# ランダムな数値を扱う
import random
random.randint(1, 100)

91

In [320]:
# 外部モジュール 行列
import numpy as np
npone = np.ones([5,5,5])
print(npone)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [321]:
npone[1]

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [329]:
for i in range(5):
    npone[i] = (i+1)*2

In [330]:
npone

array([[[ 2.,  2.,  2.,  2.,  2.],
        [ 2.,  2.,  2.,  2.,  2.],
        [ 2.,  2.,  2.,  2.,  2.],
        [ 2.,  2.,  2.,  2.,  2.],
        [ 2.,  2.,  2.,  2.,  2.]],

       [[ 4.,  4.,  4.,  4.,  4.],
        [ 4.,  4.,  4.,  4.,  4.],
        [ 4.,  4.,  4.,  4.,  4.],
        [ 4.,  4.,  4.,  4.,  4.],
        [ 4.,  4.,  4.,  4.,  4.]],

       [[ 6.,  6.,  6.,  6.,  6.],
        [ 6.,  6.,  6.,  6.,  6.],
        [ 6.,  6.,  6.,  6.,  6.],
        [ 6.,  6.,  6.,  6.,  6.],
        [ 6.,  6.,  6.,  6.,  6.]],

       [[ 8.,  8.,  8.,  8.,  8.],
        [ 8.,  8.,  8.,  8.,  8.],
        [ 8.,  8.,  8.,  8.,  8.],
        [ 8.,  8.,  8.,  8.,  8.],
        [ 8.,  8.,  8.,  8.,  8.]],

       [[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]]])

In [331]:
np.sqrt(npone)

array([[[1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356],
        [1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356],
        [1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356],
        [1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356],
        [1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356]],

       [[2.        , 2.        , 2.        , 2.        , 2.        ],
        [2.        , 2.        , 2.        , 2.        , 2.        ],
        [2.        , 2.        , 2.        , 2.        , 2.        ],
        [2.        , 2.        , 2.        , 2.        , 2.        ],
        [2.        , 2.        , 2.        , 2.        , 2.        ]],

       [[2.44948974, 2.44948974, 2.44948974, 2.44948974, 2.44948974],
        [2.44948974, 2.44948974, 2.44948974, 2.44948974, 2.44948974],
        [2.44948974, 2.44948974, 2.44948974, 2.44948974, 2.44948974],
        [2.44948974, 2.44948974, 2.44948974, 2.44948974, 2.44948974],
        [2.44948

In [349]:
nprand = np.random.random([5,5]) * 10

In [350]:
# 外部モジュール pandas 
import pandas as pd
df = pd.DataFrame(nprand)


In [351]:
df

0         1         2         3         4
0  0.103603  7.241046  7.295030  6.406875  5.719900
1  3.375654  6.655447  1.864919  9.778661  4.720756
2  2.068680  1.074914  7.649233  7.953696  8.155847
3  0.622424  3.649479  2.979007  5.229703  1.492436
4  7.962168  3.826356  8.540931  6.250254  9.626115

In [353]:
import plotly.express as px
px.scatter(df, x=df.index, y=0)

ModuleNotFoundError: No module named 'plotly'

## 関数の定義
- これを行うことにより、再利用が可能に
- defを使って定義
- マルチバイトの名前も可能
- ここにも新機能が！
    - New!! 位置専用引数デバッグ用機能

In [166]:
def 何とかパイ(nantoka):
    print(f"{nantoka}python")

In [167]:
何とかパイ("はんなり")

はんなりpython


In [72]:
# フィボナッチ数列を求める関数

def fib(n):
    fiblist = []
    a, b = 0, 1
    while a < n:
        fiblist.append(a)
        a, b = b, a+b
    return fiblist
        

In [73]:
fib(100)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

## 関数の引数の設定方法
### デフォルトの引数値
- デフォルト引数を持たないもの（位置引数 positional arguments）
- 持つものを引数に設定できる　（キーワード引数 keyword arguments）
- 位置引数はキーワード引数の前に置く
- そうすると引数をすべて与えなくても関数が動く

In [163]:
def order_three(drink, main="ハンバーガ", side="サラダ"):
    print(f"私の注文は、飲み物：{drink}、メイン：{main}、サイド：{side}でお願いします。")
    

In [164]:
def misorder_three(main="ハンバーガ", side="サラダ", drink):
    print(f"私の注文は、飲み物：{main}、メイン：{side}、サイド：{drink}でお願いします。")
    

SyntaxError: non-default argument follows default argument (<ipython-input-164-8c05d57b06a0>, line 1)

In [165]:
order_three("コーラ")

私の注文は、飲み物：コーラ、メイン：ハンバーガ、サイド：サラダでお願いします。


In [80]:
order_three("コーラ", main="ラーメン")

私の注文は、飲み物：コーラ、メイン：ラーメン、サイド：サラダでお願いします。


In [81]:
# 何も指定しないとエラーになる
order_three()

TypeError: order_three() missing 1 required positional argument: 'drink'

### New f-stringにも新機能が！！！
- f"{変数=}"の形で代入を確認できる
- f-string周りは色々変更があったがこれは良いような

In [157]:
def order_three(drink, main="ハンバーガ", side="サラダ"):
    print(f"私の注文は、飲み物：{drink=}、メイン：{main=}、サイド：{side=}でお願いします。")
   

In [158]:
order_three("ファンタ")

私の注文は、飲み物：drink='ファンタ'、メイン：main='ハンバーガ'、サイド：side='サラダ'でお願いします。


In [92]:
def test_args(*args):
    for a in args:
        print("「{}」".format(a))

In [93]:
test_args("こんにちは", "こんにちは", "最近どうですか？", "良い感じです")

「こんにちは」
「こんにちは」
「最近どうですか？」
「良い感じです」


In [129]:
def hanpy1(one, two, three, four="ウィングス京都"):
    print(one, two, three, four)

In [130]:
hanpy1("スプーキーズさん", "マネーフォワードさん", "さんさんさん")

スプーキーズさん マネーフォワードさん さんさんさん ウィングス京都


### python3.0でキーワード専用引数を指定できるように！「*」

In [131]:
def hanpy1(one, two, three, *,four="ウィングス京都"):
    print(one, two, three, four)

In [132]:
def hanpy1(one, two, *,three, four="ウィングス京都"):
    print(one, two, three, four)

In [133]:
hanpy1("スプーキーズさん", "マネーフォワードさん", "さんさんさん")

TypeError: hanpy1() takes 2 positional arguments but 3 were given

In [134]:
hanpy1("スプーキーズさん", "マネーフォワードさん", three="さんさんさん")

スプーキーズさん マネーフォワードさん さんさんさん ウィングス京都


### python3.8で位置専用引数を指定できるように 「/」

In [141]:
def hanpy1(one, two, /,three, four="ウィングス京都"):
    print(one, two, three, four)

In [143]:
hanpy1("スプーキーズさん", two="マネーフォワードさん", three="さんさんさん")

TypeError: hanpy1() got some positional-only arguments passed as keyword arguments: 'two'

### class
- クラスを作成します
- 初心者にとってクラスは分かりにくいです
- 今回も関数とクラスどう違うの？ってコメントがありました（来られてないかも）
- 私も最近分かりました
- 大阪Pythonの会の資料が分かりやすいです。https://scrapbox.io/PythonOsaka/%E3%82%AF%E3%83%A9%E3%82%B9_(%E8%A9%B3%E7%B4%B0%E7%89%88)

In [151]:
dir(9)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 'real',
 'to_bytes']

In [152]:
dir("string")

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',


In [175]:
class human:
    
    def __init__(self, name, height, weight, shoe_size):
        self.name = name
        self.height = height
        self.weight = weight
        self.shoe_size = shoe_size
    
    def introduce(self):
        print(f"私の名前は{self.name}です。靴のサイズは{self.shoe_size}です。")

In [176]:
h = human("hide", 180, 75, 28)

In [178]:
print(h.name)
print(h.weight)
h.introduce()

hide
75
私の名前はhideです。靴のサイズは28です。


In [162]:
dir(h)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'height',
 'introduce',
 'name',
 'shoe_size',
 'weight']

## 継承
- クラスは親の秘伝のたれを発展させることができます
- 継承おもろい！

In [289]:
class human_diary(human):
    
    def __init__(self, name, tall, weight, shoe_size):
        super().__init__(name, tall, weight, shoe_size)
        self.diary = {}
        
    def write_diary(self, date, article):
        self.diary[date] = article
        
    def know_date(self):
        return self.diary.keys()
    
    def read_diary(self):
        if len(self.diary) == 0:
            print("Diary does not exist.")
        return self.diary

In [219]:
hi= human_diary("hide", 180, 75, 28)

In [220]:
hi.name

'hide'

In [221]:
hi.write_diary("2019/11/07", "いまはんなりPythonの準備をしています。windowsでjupyter notebookが動かないことが分かりました。")
hi.write_diary("2019/11/09", "いまはんなりPythonの準備をしています。もうちょっとで終わりです")

In [222]:
hi.read_diary()

{'2019/11/07': 'いまはんなりPythonの準備をしています。windowsでjupyter notebookが動かないことが分かりました。',
 '2019/11/09': 'いまはんなりPythonの準備をしています。もうちょっとで終わりです'}

In [223]:
hi.know_date()

dict_keys(['2019/11/07', '2019/11/09'])

In [217]:
d["2019/11/07"]

'いまはんなりPythonの準備をしています。windowsでjupyter notebookが動かないことが分かりました。'

## 課題
- 日記をいつ書いたかわかる関数を継承を使って作成しましょう
- 日記を他人に見られないようにロック、またロックを外す関数を継承を使って作成しましょう

### エラーと例外
- プルグラムのミス / 構文エラー
- 構文的にあっているが起こるエラー / 例外

In [268]:
# 構文エラー
while True
    prnit("Hi")
    break

SyntaxError: invalid syntax (<ipython-input-268-be985d5b89e0>, line 2)

In [280]:
# 例外
10 /0

ZeroDivisionError: division by zero

In [281]:
# 例外
4 + "spam"

TypeError: unsupported operand type(s) for +: 'int' and 'str'

### 最終行にどんなエラーがあるか表示！
- 途中にミスのある部分が示される
- 致命的なエラーではない
- これらを読んでエラーが起こった際の行動をプログラムする

In [283]:
while True:
    try:
        x = int(input("Enter Number"))
        break
    except ValueError:
        print("Please enter int")

Enter Number 1.1


Please enter int


Enter Number 1


In [284]:
# エラー
int(input("type number"))

type number 1.1


ValueError: invalid literal for int() with base 10: '1.1'

In [277]:
int(y)

NameError: name 'y' is not defined

In [288]:
class B(Exception):
    pass

class C(B):
    pass

class D(C):
    pass

for cls in [B, C, D]:
    try:
        raise cls
    except D:
        print("D")
    except C:
        print("C")
    except B:
        print("B")

B
C
D


In [287]:
B

__main__.B